server:
  name: !!str "name"

# https://medium.com/building-the-system/gunicorn-3-means-of-concurrency-efbb547674b7
# Gunicorn Perf Optimization reference
wsgi:
  # bind options for WSGI/Gunicorn
  bind:
    port: !!int 8081
    ip: !!str "0.0.0.0"

  # Number of workers for WSGI. 
  workers: !!int 4

